### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by drsagitn** [gongzhitaao/tensorflow-adversarial#2]
I looked for dependencies part in the readme but didn't see it. I wondered which version of tensorflow this code is working on?

**Comment by gongzhitaao** [comment]
This was written with TF v1.1 .  I'm planning to upgrade to TF v1.3 API this week.  Since the major version is not changed, I would expect most of their APIs keep the same signature.

**Comment by gongzhitaao** [comment]
Added dependencies, *should be* TFv1.1 and onwards.  I tested with **TFv1.4**
