### ISSUE TITLE
I

### ISSUE THREAD

**Issue by Tangzixia** [gongzhitaao/tensorflow-adversarial#3]
hello，I want to test the jsma function,but I can't find ex_01.py in the repertory，so can you give me your ex_01.py?Thank you very much!!!

**Comment by gongzhitaao** [comment]
Do you use Keras?  In keras_example, there is ex_01.py.  I forgot to upload it.  The only difference is whether the model is built using Keras API or TF API.  I will upload one asap.

**Comment by gongzhitaao** [comment]
The example code has already been refactored.

**Comment by Tangzixia** [comment]
Thanks a lot,I'm sorry for missing your reply,I have handled it,Thank you!
