### ISSUE TITLE
what is adversarial data?

### ISSUE THREAD

**Issue by Mistty** [gongzhitaao/tensorflow-adversarial#4]
recently I am working on model compression and if it influenced model robustness while facing adversarial samples, I tried ex06.py on cifar10, and after generating adversarial data, it would test against adversarial test data:
print('Testing against adversarial test data')
score = model.evaluate(X_adv, y_test)
print('\nloss: {0:.4f} acc: {1:.4f}'.format(score[0], score[1]))
I am a little confused, higher accuracy means better or worse robustness? or it's not related?
so could you please explain a little about adversarial data, thx!

**Comment by gongzhitaao** [comment]
Higher accuracy means the model is more robust or the adversarial samples are not very effective.

**Comment by Mistty** [comment]
Thank you very much! Really helps!
