### ISSUE TITLE
ex_00.py for different model

### ISSUE THREAD

**Issue by Poomathi** [gongzhitaao/tensorflow-adversarial#5]
Hi,

I tried to change the model to one similar to(https://github.com/radioML/examples/blob/master/modulation_recognition/RML2016.10a_VTCNN2_example.ipynb) this model. Where total params is 2,830,427 (way more than your simple model). While generating adversarial crafting graph, I receive the following error
Traceback (most recent call last):
  File "RML_TOS.py", line 121, in <module>
    x_adv = fgsm(_model_fn, x, epochs=9, eps=0.0001)
  File "/home/pduraisamy/Adversarial/adversarial/fgsm.py", line 23, in fgsm
    ybar = model(x_adv)
  File "RML_TOS.py", line 117, in _model_fn
    logits_, = ybar.op.inputs
ValueError: too many values to unpack
Exception AttributeError: "'NoneType' object has no attribute 'path'" in <function remove at 0x7fb07c21f140> ignored

Does it mean it couldn't handle deep network? Appreciate your help.

**Comment by gongzhitaao** [comment]
Did you use Theano backend or Tensorflow backend?  The `ValueError: too many values to unpack` seems to indicate that you are using Theano as backend.

**Comment by Poomathi** [comment]
I am using tensorflow as backend.
Using TensorFlow backend.

**Comment by Poomathi** [comment]
Below is my model structure if it helps
 model = Sequential([
         ZeroPadding2D(padding=(0,2),input_shape=input_shape),
         Conv2D(filters=256, kernel_size=(1, 3), padding='valid',activation="relu", name="conv1", kernel_initializer='glorot_uniform'),
         Dropout(0.5),
         ZeroPadding2D(padding=(0,2)),
         Conv2D(filters=80, kernel_size=(2, 3), padding='valid',activation="relu", name="conv2", kernel_initializer='glorot_uniform'),
         Dropout(0.5),
         Flatten(),
         Dense(256, activation="relu", name="dense1", kernel_initializer='he_normal' ),
         Dropout(0.5),
         Dense(11, name="dense2", kernel_initializer='he_normal'),
         Activation('softmax'),
         Reshape([11])])
since I am new to tensorflow, I am struggling to figure out why it produces ValueError at line logits_, = ybar.op.inputs. Any help is appreciated.Thanks.

**Comment by Poomathi** [comment]
After removing last layer Reshape([11]). it works perfectly fine. Not sure why it didn't like the Reshape layer.

**Comment by gongzhitaao** [comment]
It makes sense.  The `ybar.op.inputs` is the input for `softmax` operation, i.e., logits, input for `Reshape` operation may be different, you could print `ybar.op` to see what's available.  It is Keras internal implementation, this `ybar.op.inputs` is more of a hack, and might be changed in later Keras version.
